image: python:3.8-slim

stages:
  - deploy

before_script:
   - pip install twine
   - pip install numpy
   - pip install astropy
   - pip install sphinx sphinx-argparse
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - echo $STAGING_USERNAME
    - echo $TWINE_USERNAME
    - cd dist/
    - twine upload --verbose --repository-url $PYPITEST_REPOSITORY_URL pyspextools*
  only:
    - master
  except:
    - tags
  
deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - cd dist/
    - twine upload pyspextools*
  only:
    - tags
