image: python:3.6-slim

stages:
  - deploy

before_script:
   - pip install twine
   - pip install numpy
   - pip install astropy
   - pip install sphinx sphinx-argparse
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - echo $STAGING_USERNAME
    - echo $TWINE_USERNAME
    - twine upload --repository-url $PYPITEST_REPOSITORY_URL dist/*
  only:
    - master
  except:
    - tags
  
deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
